# Generated by Django 2.0 on 2019-01-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='format',
            field=models.CharField(default='textplain', max_length=255),
        ),
    ]
