# Generated by Django 2.0 on 2019-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20190101_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='format',
            field=models.CharField(default='text/plain', max_length=255),
        ),
    ]
