# Generated by Django 2.0 on 2019-01-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20190101_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selector',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selector',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
