# Generated by Django 2.0 on 2019-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20190101_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selector',
            name='image_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selector',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selector',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selector',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
