# Generated by Django 2.0 on 2019-01-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '__first__'),
        ('annotations', '0006_auto_20190101_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.EventImage'),
        ),
        migrations.AlterField(
            model_name='target',
            name='source',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
